### ISSUE TITLE
do you plan to add a short instruction?

### ISSUE THREAD

**Issue by DongChen06** [bitsauce/Carla-ppo#1]
Great resource, it would be better if  you can add a short instruction based on your implementation. Thank you!!

**Comment by bitsauce** [comment]
Hi Derekabc!
You are right, I should add some instruction. As it stands, this code is part of my master's thesis which is due soon. But once I'm done writing it I'll get around to update the README

– Marcus

**Comment by bitsauce** [comment]
Committed a somewhat final version of the README with instruction now
- Marcus
