### ISSUE TITLE
screen doesn't move at some episodes

### ISSUE THREAD

**Issue by jizeyu** [bitsauce/Carla-ppo#14]
Hi
    When I run the PPO agent, at some episodes, the throttle of the car is not zero but the screen doesn't move and refresh.Do you know why and how to deal with it.

THANK YOU

**Comment by HFY123** [comment]
> Hi
> When I run the PPO agent, at some episodes, the throttle of the car is not zero but the screen doesn't move and refresh.Do you know why and how to deal with it.
> 
> THANK YOU

I met the same problem...Still don't know how to solve it.

**Comment by jizeyu** [comment]
> I met the same problem...Still don't know how to solve it.

Do you know how to deal with it now? My training curve fluctuates a lot because of this problem.

**Comment by HFY123** [comment]
> > I met the same problem...Still don't know how to solve it.
> 
> Do you know how to deal with it now? My training curve fluctuates a lot because of this problem.

Don't know how to solve it, I can only shorten the low_speed_timer in reward_function.py to make it stop a shorter time......
