### ISSUE TITLE
Exception: Expected to find directory "dist" under ${CARLA_ROOT}!

### ISSUE THREAD

**Issue by chrisyan** [bitsauce/Carla-ppo#17]
Hi Bitsauce,
I have added the environment variable to bachrc file and sourced it, something like this 
"export CARLA_ROOT=/home/chris/carla
export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.10-py3.6-linux-x86_64.egg"

But I still get an error when I run command " python3 run_eval.py --model_name pretrained_agent -start_carla
".
The error is ：
Traceback (most recent call last):
  File "run_eval.py", line 117, in <module>
    start_carla=args.start_carla)
  File "/home/chris/Carla-ppo-master/CarlaEnv/carla_lap_env.py", line 101, in __init__
    raise Exception("Expected to find directory \"dist\" under ${CARLA_ROOT}!")
Exception: Expected to find directory "dist" under ${CARLA_ROOT}!

Could you give me a tipp ? I appreciate.

Yours,
Chris

**Comment by lmc19970711** [comment]
hello, I have the same problem, did you solve it?

**Comment by lmc19970711** [comment]
> Hi Bitsauce,
> I have added the environment variable to bachrc file and sourced it, something like this
> "export CARLA_ROOT=/home/chris/carla
> export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.10-py3.6-linux-x86_64.egg"
> 
> But I still get an error when I run command " python3 run_eval.py --model_name pretrained_agent -start_carla
> ".
> The error is ：
> Traceback (most recent call last):
> File "run_eval.py", line 117, in
> start_carla=args.start_carla)
> File "/home/chris/Carla-ppo-master/CarlaEnv/carla_lap_env.py", line 101, in **init**
> raise Exception("Expected to find directory "dist" under ${CARLA_ROOT}!")
> Exception: Expected to find directory "dist" under ${CARLA_ROOT}!
> 
> Could you give me a tipp ? I appreciate.
> 
> Yours,
> Chris

hello, I have the same problem, did you solve it?

**Comment by bitsauce** [comment]
Hi @lmc19970711 ! Have you verified that there is a directory called `dist` in your `${CARLA_ROOT}` dir?

If there isn't, I think you have to run the setup script to compile a binary to run, see: https://carla.readthedocs.io/en/0.9.5/how_to_build_on_linux/ (Note: this doc is for 0.9.5, change the version in the URL if you want to try another version)

If I recall correctly, it is the `make launch` step that actually generates the `dist` folder
