### ISSUE TITLE
Can't find dist under ${CARLA_ROOT}

### ISSUE THREAD

**Issue by Oroduin** [bitsauce/Carla-ppo#18]
Hi, bitsause
I have added carla_root by bashrc using:
export CARLA_ROOT=home/dc2-user/carla
export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.10-py3.6-linux-x86_64.egg:${CARLA_ROOT}/PythonAPI/carla/agents:${CARLA_ROOT}/PythonAPI/carla

And I don't know why carla_lap_env.py can't find dist, could you please help me?

**Comment by bitsauce** [comment]
Hey!

I think you have to install the `.egg` files rather than adding them to your `PYTHONPATH`. According to [this section](https://carla.readthedocs.io/en/latest/build_system/#pythonapi) of the Carla docs, this how you would do that:

`easy_install3 --user --no-deps PythonAPI/dist/carla-0.9.10-py3.6-linux-x86_64.egg`

After installing the library this way, you should be able to just start `python` in the terminal and call `import carla` without any error

(Addendum, I'm not sure the repo will work with Carla 0.9.10 without any modifications but it's worth trying!)

Let me know if this fixes your problem :)

**Comment by Oroduin** [comment]
Hi!
Sorry about the late response.
I think the reason is not about egg files, because I have installed egg by
pip3 install -e ~/carla/PythonAPI/carla/dist/carla-0.9.10-py3.6-linux-x86_64
And import carla in python successfully.
The last point you mentioned is right, it indeed needs some modifications in carla_lap_env.py.
 # Start CARLA from CARLA_ROOT
        self.carla_process = None
        if start_carla:
            if "CARLA_ROOT" not in os.environ:
                raise Exception("${CARLA_ROOT} has not been set!")
            dist_dir = os.path.join(os.environ["CARLA_ROOT"], "Dist")
            if not os.path.isdir(dist_dir):
                raise Exception("Expected to find directory \"Dist\" under ${CARLA_ROOT}!")
            sub_dirs = [os.path.join(dist_dir, sub_dir) for sub_dir in os.listdir(dist_dir) if os.path.isdir(os.path.join(dist_dir, sub_dir))]
            if len(sub_dirs) == 0:
                raise Exception("Could not find a packaged distribution of CALRA! " +
                                "(try building CARLA with the \"make package\" " +
                                "command in ${CARLA_ROOT})")
            sub_dir = sub_dirs[0]
            carla_path = os.path.join(sub_dir, "LinuxNoEditor", "CarlaUE4.sh")
            launch_command = [carla_path]
            launch_command += ["Town07"]
            if synchronous: launch_command += ["-benchmark"]
            launch_command += ["-fps=%i" % fps]
            print("Running command:")
            print(" ".join(launch_command))
            self.carla_process = subprocess.Popen(launch_command, stdout=subprocess.PIPE, universal_newlines=True)
            print("Waiting for CARLA to initialize")
            for line in self.carla_process.stdout:
                if "LogCarla: Number Of Vehicles" in line:
                    break
            time.sleep(2)
And I changed Dist to dist, but it still can't find the dist through os.path.join() 
So I decide to remove those test codes.

**Comment by Oroduin** [comment]
After I deleted those codes, I encountered a new problem: the carla_lap_env.py would stick in these steps:

Spawned actor "vehicle.lincoln.mkz2017"
Spawned actor "sensor.camera.rgb"
Spawned actor "sensor.camera.rgb"

But I don't know the reason.

**Comment by lmc19970711** [comment]
> After I deleted those codes, I encountered a new problem: the carla_lap_env.py would stick in these steps:
> 
> Spawned actor "vehicle.lincoln.mkz2017"
> Spawned actor "sensor.camera.rgb"
> Spawned actor "sensor.camera.rgb"
> 
> But I don't know the reason.

> Hi, bitsause
> I have added carla_root by bashrc using:
> export CARLA_ROOT=home/dc2-user/carla
> export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.10-py3.6-linux-x86_64.egg:${CARLA_ROOT}/PythonAPI/carla/agents:${CARLA_ROOT}/PythonAPI/carla
> 
> And I don't know why carla_lap_env.py can't find dist, could you please help me?

hello, I have the same problem, did you solve it?

**Comment by Oroduin** [comment]
> > After I deleted those codes, I encountered a new problem: the carla_lap_env.py would stick in these steps:
> > Spawned actor "vehicle.lincoln.mkz2017"
> > Spawned actor "sensor.camera.rgb"
> > Spawned actor "sensor.camera.rgb"
> > But I don't know the reason.
> 
> > Hi, bitsause
> > I have added carla_root by bashrc using:
> > export CARLA_ROOT=home/dc2-user/carla
> > export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.10-py3.6-linux-x86_64.egg:${CARLA_ROOT}/PythonAPI/carla/agents:${CARLA_ROOT}/PythonAPI/carla
> > And I don't know why carla_lap_env.py can't find dist, could you please help me?
> 
> hello, I have the same problem, did you solve it?

No, which kind of carla's version did you installed?

**Comment by lmc19970711** [comment]
> > > After I deleted those codes, I encountered a new problem: the carla_lap_env.py would stick in these steps:
> > > Spawned actor "vehicle.lincoln.mkz2017"
> > > Spawned actor "sensor.camera.rgb"
> > > Spawned actor "sensor.camera.rgb"
> > > But I don't know the reason.
> > 
> > 
> > > Hi, bitsause
> > > I have added carla_root by bashrc using:
> > > export CARLA_ROOT=home/dc2-user/carla
> > > export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.10-py3.6-linux-x86_64.egg:${CARLA_ROOT}/PythonAPI/carla/agents:${CARLA_ROOT}/PythonAPI/carla
> > > And I don't know why carla_lap_env.py can't find dist, could you please help me?
> > 
> > 
> > hello, I have the same problem, did you solve it?
> 
> No, which kind of carla's version did you installed?
![image](https://user-images.githubusercontent.com/57525636/115106499-c5a90a80-9f97-11eb-8940-67370b0828c3.png)
This is my method,can run CARLA and pygame, but no interface, I don't know why. You can try.

**Comment by Oroduin** [comment]
> > > > After I deleted those codes, I encountered a new problem: the carla_lap_env.py would stick in these steps:
> > > > Spawned actor "vehicle.lincoln.mkz2017"
> > > > Spawned actor "sensor.camera.rgb"
> > > > Spawned actor "sensor.camera.rgb"
> > > > But I don't know the reason.
> > > 
> > > 
> > > > Hi, bitsause
> > > > I have added carla_root by bashrc using:
> > > > export CARLA_ROOT=home/dc2-user/carla
> > > > export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.10-py3.6-linux-x86_64.egg:${CARLA_ROOT}/PythonAPI/carla/agents:${CARLA_ROOT}/PythonAPI/carla
> > > > And I don't know why carla_lap_env.py can't find dist, could you please help me?
> > > 
> > > 
> > > hello, I have the same problem, did you solve it?
> > 
> > 
> > No, which kind of carla's version did you installed?
> > ![image](https://user-images.githubusercontent.com/57525636/115106499-c5a90a80-9f97-11eb-8940-67370b0828c3.png)
> > This is my method,can run CARLA and pygame, but no interface, I don't know why. You can try.

The version of yours matches the recommendation, the method you used is the same as mine, and did you stuck in Spawned actor "sensor.camera.rgb" in the terminal? If so, I guess this modification is wrong.

**Comment by bitsauce** [comment]
I, unfortunately, don't have CARLA setup at the moment, but I have a couple of question to you @Oroduin ; when you get these output messages:

> Spawned actor "vehicle.lincoln.mkz2017"
> Spawned actor "sensor.camera.rgb"
> Spawned actor "sensor.camera.rgb"

Is a car spawned into the world?

Also, how are you running the code? Are you running the environment script directly (e.g. are running `carla_lap_env.py`) or are you running `train.py`/`run_eval.py`?

**Comment by Oroduin** [comment]
> I, unfortunately, don't have CARLA setup at the moment, but I have a couple of question to you @Oroduin ; when you get these output messages:
> 
> > Spawned actor "vehicle.lincoln.mkz2017"
> > Spawned actor "sensor.camera.rgb"
> > Spawned actor "sensor.camera.rgb"
> 
> Is a car spawned into the world?
> 
> Also, how are you running the code? Are you running the environment script directly (e.g. are running `carla_lap_env.py`) or are you running `train.py`/`run_eval.py`?


Thank you for your reply!
Actually, I didn't see any images. The pygame window is black.
I run code as your instructions: python run_eval.py/train.py --model_name pretrained_agent -start_carla
The resulting screenshot:
![3ed3acad9ee439075c9c09c17ba6019](https://user-images.githubusercontent.com/80673243/115141405-9ca77900-a06e-11eb-9e43-cc8c7645ca1d.png)

**Comment by bitsauce** [comment]
Have you checked if there is a car in the simulator window behind the `pygame` window? The car should spawn there. Also, I think you can manually start the simulator beforehand, and running the environment with `start_carla=False` to see the output of the simulator itself in the terminal window that you started CARLA with; it should tell you what it is spawning or if there is any other issues

**Comment by Oroduin** [comment]
> Have you checked if there is a car in the simulator window behind the `pygame` window? The car should spawn there. Also, I think you can manually start the simulator beforehand, and running the environment with `start_carla=False` to see the output of the simulator itself in the terminal window that you started CARLA with; it should tell you what it is spawning or if there is any other issues

The simulator window is the default, no car in there, and the maps didn't change to Town 7
![image](https://user-images.githubusercontent.com/80673243/115143653-34ab5f80-a07b-11eb-94b7-9b7db344edac.png)
And I have Add +MapsToCook=(FilePath="/Game/Carla/Maps/Town07") to Unreal/CarlaUE4/Config/DefaultGame.ini

**Comment by bitsauce** [comment]
Hmm, I believe a car is supposed to spawn regardless of the map. But let's see if it happens if we get `Town07` working.

Do you have a file called `${CARLA_ROOT}/Unreal/CarlaUE4/Contents/Carla/Maps/Town.07.umap` or something similar?

If you see the other maps there, but not `Town07`, then grab `Town07` from here: https://github.com/carla-simulator/carla/releases/tag/0.9.5

IIRC the map had to be downloaded separately

**Comment by Oroduin** [comment]
> Hmm, I believe a car is supposed to spawn regardless of the map. But let's see if it happens if we get `Town07` working.
> 
> Do you have a file called `${CARLA_ROOT}/Unreal/CarlaUE4/Contents/Carla/Maps/Town.07.umap` or something similar?
> 
> If you see the other maps there, but not `Town07`, then grab `Town07` from here: https://github.com/carla-simulator/carla/releases/tag/0.9.5
> 
> IIRC the map had to be downloaded separately

I may have found the reasons:
First, I didn't have Town07.map, so I change it to Town05.
But still can't run, so I checked the GPU/CPU occupancy rate, it's really high.
So I guess my GPU card is too weak to afford the Carla.
Thank you for your answers!

**Comment by bitsauce** [comment]
> But still can't run, so I checked the GPU/CPU occupancy rate, it's really high.
> So I guess my GPU card is too weak to afford the Carla.

Ah, yeah, it could be. You should at least be able to move somewhat smoothly around in the simulator with WASD + Mouse. If that isn't the case then your GPU might indeed be struggling.

Feel free to update this thread you get any further/have more questions :)

**Comment by Basavaraj-PN** [comment]
Do `make package`  after make PythonAPI

**Comment by lovesuiyue** [comment]
I also encountered the same problem. How did I solve it @bitsauce  @Oroduin

**Comment by Basavaraj-PN** [comment]
> I also encountered the same problem. How did I solve it @bitsauce @Oroduin

Did you do `make package` after `make PythonAPI` ?

**Comment by lovesuiyue** [comment]
> > I also encountered the same problem. How did I solve it @bitsauce @Oroduin
> 
> Did you do `make package` after `make PythonAPI` ?

I Do

**Comment by lovesuiyue** [comment]
and  Have you solved these problems in the end @Basavaraj-PN

**Comment by Basavaraj-PN** [comment]
@lovesuiyue  yes, I solved it.

**Comment by Oroduin** [comment]
I had enough for you! Why did you ask questions before you try it. Besides, most of your questions had solutions in issues, and you don't look carefully about author's instructions, just ask these stupid questions. 

> I also encountered the same problem. How did I solve it @bitsauce @Oroduin

**Comment by lovesuiyue** [comment]
I tried, but I couldn't @Oroduin

**Comment by Oroduin** [comment]
> Do `make package` after make PythonAPI

Hi, sorry about later response.
I didn't use build from source version, so I just changed the code and activate it manually. I think your solution is right, thanks for your advice.
