### ISSUE TITLE
car stops for some episodes

### ISSUE THREAD

**Issue by DongChen06** [bitsauce/Carla-ppo#2]
I just got the car moving and start training.  But i find most of the episodes, the car stops at the starting point, then a new episode would start.  Do you know what may cause this?  Thank you very much
![image](https://user-images.githubusercontent.com/25771207/57490481-6b6d7e00-7287-11e9-8bc5-104cd0fba437.png)

**Comment by bitsauce** [comment]
The code is written with Town07 in mind, so it might not work that well with other maps out-of-the-box. I'll get around to verify that everything works in its current state soon

– Marcus

**Comment by DongChen06** [comment]
Hi, marcus, thank you for your reply. If it is possible, i wonder whether I can have an opportunity to read your thesis, so i can have a better understanding on this repository. 
BTW, would you like to share a pretrained model trained on PPO as it's time-consuming. 
Thank you so much !!

**Comment by weizhaoji** [comment]
hello, do you know how to run the make package command in the root directory of CARLA and add the town07 to the make package?

**Comment by bitsauce** [comment]
@Derekabc Don't know if you're still interested this project, but I thought I would let you know that I added a pretrained model to this repo about a month ago! (That model isn't as good as some of the earlier ones though, unfortunately)

@weizhaoji See #7
