### ISSUE TITLE
Carla-ppo-master/common.py-in load_vae: raise Exception("Failed to load VAE")

### ISSUE THREAD

**Issue by 1JIEZHAO** [bitsauce/Carla-ppo#5]
hello, bitsauce, thanks for you job ! I want to run the trained agent and I do as you said in the README.md with carla-0.9.5 releases.
When I run the "python3 run_eval.py --model_name TODO", there is an error:
Traceback (most recent call last):
  File "run_eval.py", line 83, in <module>
    vae = load_vae(args.vae_model, args.vae_z_dim, args.vae_model_type)
  File "…Carla-ppo-master/common.py", line 26, in load_vae
    raise Exception("Failed to load VAE")
Exception: Failed to load VAE

I look into the file path "bce_cnn_zdim64_beta1_kl_tolerance0.0_data/" and find it's empty and this file is also not  in your project, but the vae_model path in run_eval.py is: parser.add_argument("--vae_model", type=str, default="bce_cnn_zdim64_beta1_kl_tolerance0.0_data").

So would you help me find out why this error is occurred?

**Comment by weizhaoji** [comment]
hello, do you know how to run the make package command in the root directory of CARLA and add the town07 to the make package?

**Comment by bitsauce** [comment]
@1JIEZHAO Sorry. There was no pre-trained agent included in the repository at the time, but there is one now! (Although I wasn't able to train it to perform as well as it did previously - given my limited time these days)
