### ISSUE TITLE
how can I use the Town07_0.9.5?

### ISSUE THREAD

**Issue by weizhaoji** [bitsauce/Carla-ppo#7]

**Comment by bitsauce** [comment]
Hi,

Make sure that you have the following line in `CarlaUE4/Config/DefaultGame.ini`:

`+MapsToCook=(FilePath="/Game/Carla/Maps/Town07")`

Then package CARLA again (with `make package`).

Then run the packaged version of CARLA (located in `Dist/xxxxx/LinuxNoEditor`) with `./CarlaUE4.sh Town07`

You should now see Town07 and should be able to run the training provided you set up the CARLA_ROOT env variable as briefly described [here](https://github.com/bitsauce/Carla-ppo#running-a-trained-agent).

Good luck!
